const $=s=>document.querySelector(s);
const KEY="ayush9845_neet_command_center_v1";
const defaults={profile:{name:"Ayush Kumar",handle:"@Ayush9845",target:720,college:"AIIMS New Delhi"},hours:0,streak:0,tasks:[],scores:[],ncert:{Physics:0,Chemistry:0,Biology:0},subject:{Biology:42,Chemistry:28,Physics:35},logs:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaults);
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(m){let t=$("#toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",1800)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
const pages={
dashboard:["Dashboard",dashboard],
planner:["Daily Planner",planner],
ncert:["NCERT Tracker",ncert],
biology:["Biology",()=>subjectPage("Biology")],
chemistry:["Chemistry",()=>subjectPage("Chemistry")],
physics:["Physics",()=>subjectPage("Physics")],
questions:["Question Bank",questions],
tests:["Mock Tests",tests],
performance:["Performance",performance],
streak:["Study Streak",streak],
pomodoro:["Pomodoro",pomodoro],
progress:["Progress Graphs",progress],
settings:["Settings",settings]
};
function showPage(p){let [title,fn]=pages[p];$("#pageTitle").textContent=title;$("#content").innerHTML=fn();document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(innerWidth<900)$("#sidebar")?.classList.remove("open");wire(p)}
function dashboard(){let target=data.profile.target||720,days=Math.max(0,Math.ceil((new Date("2027-05-02")-new Date())/864e5));return `<div class="grid">
<div class="span-8 hero"><span class="pill">@Ayush9845 • NEET 2027</span><h2>Build your score, one day at a time.</h2><p class="muted">Your personal command center for NCERT, questions, mocks and revision.</p><div class="cards-row"><div><div class="small muted">Days remaining</div><div class="big accent">${days}</div></div><div><div class="small muted">Target score</div><div class="big">${target}</div></div><div><div class="small muted">Study hours</div><div class="big">${data.hours}</div></div><div><div class="small muted">Streak</div><div class="big orange">${data.streak} 🔥</div></div></div></div>
<div class="span-4 card"><h3 class="section-title">Today's focus</h3><div class="stack"><input class="input" id="quickTask" placeholder="Add a task..."><button class="btn" onclick="addTask()">＋ Add task</button><div class="muted small">Completed: ${data.tasks.filter(t=>t.done).length}/${data.tasks.length}</div></div></div>
<div class="span-6 card"><h3 class="section-title">Subject progress</h3>${["Biology","Chemistry","Physics"].map(s=>`<div class="stack"><div class="row"><b>${s}</b><span class="small muted">${data.subject[s]}%</span></div><div class="progress"><i style="width:${data.subject[s]}%"></i></div></div>`).join("")}</div>
<div class="span-6 card"><h3 class="section-title">Quick actions</h3><div class="cards-row"><button class="btn secondary" onclick="showPage('pomodoro')">⏱️ Focus</button><button class="btn secondary" onclick="showPage('tests')">🎯 Add Mock</button><button class="btn secondary" onclick="showPage('planner')">📅 Plan</button><button class="btn secondary" onclick="showPage('performance')">📊 Analyze</button></div></div>
<div class="span-12 card"><h3 class="section-title">Today's tasks</h3>${taskList()}</div></div>`}
function taskList(){if(!data.tasks.length)return `<div class="empty">No tasks yet. Add your first task above.</div>`;return `<div class="list">${data.tasks.map((t,i)=>`<label class="task"><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${i})"><span style="${t.done?"text-decoration:line-through;color:#65738c":""}">${esc(t.text)}</span><button class="icon-btn" style="margin-left:auto" onclick="deleteTask(${i})">×</button></label>`).join("")}</div>`}
function planner(){return `<div class="grid"><div class="span-8 card"><h3 class="section-title">Daily Planner</h3><div class="row"><input class="input" id="taskInput" placeholder="e.g. NCERT: Molecular Basis of Inheritance"><button class="btn" onclick="addTaskFromPlanner()">Add</button></div><br>${taskList()}</div><div class="span-4 card"><h3 class="section-title">Daily target</h3><div class="metric accent">${data.hours} h</div><p class="muted">Log focused study time.</p><input class="input" id="hoursInput" type="number" min="0" step=".25" placeholder="Hours today"><br><br><button class="btn" onclick="logHours()">Save hours</button></div></div>`}
function ncert(){return `<div class="grid"><div class="span-12 card"><h3 class="section-title">NCERT Tracker</h3><p class="muted">Update your completion percentage for each subject.</p>${["Biology","Chemistry","Physics"].map(s=>`<div class="stack" style="margin:18px 0"><div class="row"><b>${s}</b><span>${data.ncert[s]}%</span></div><input type="range" min="0" max="100" value="${data.ncert[s]}" oninput="updateNcert('${s}',this.value)"><div class="progress"><i style="width:${data.ncert[s]}%"></i></div></div>`).join("")}</div></div>`}
function subjectPage(s){let chapters=s==="Biology"?["The Living World","Biological Classification","Plant Kingdom","Animal Kingdom","Cell: The Unit of Life","Biomolecules","Human Physiology","Genetics","Ecology"]:s==="Chemistry"?["Some Basic Concepts","Structure of Atom","Chemical Bonding","Thermodynamics","Equilibrium","Redox Reactions","Organic Basics","Hydrocarbons","Biomolecules"]:["Units & Measurements","Motion","Laws of Motion","Work, Energy & Power","Rotational Motion","Gravitation","Thermodynamics","Electrostatics","Current Electricity"];return `<div class="grid"><div class="span-8 card"><h3 class="section-title">${s} — Chapter Tracker</h3><div class="list">${chapters.map((c,i)=>`<label class="task"><input type="checkbox" onchange="chapterDone('${s}',${i},this.checked)"><span>${c}</span><span class="pill" style="margin-left:auto">Chapter ${i+1}</span></label>`).join("")}</div></div><div class="span-4 card"><h3 class="section-title">${s} notes</h3><textarea class="input" id="notes-${s}" rows="8" placeholder="Write quick revision notes..."></textarea><br><br><button class="btn" onclick="saveSubjectNotes('${s}')">Save notes</button></div></div>`}
function questions(){return `<div class="grid"><div class="span-8 card"><span class="pill">Practice Mode</span><h2>Question Bank</h2><p class="muted">A starter workspace for your own MCQs.</p><div class="task"><b>Q1.</b><span>Which process converts light energy into chemical energy in plants?</span></div><div class="list" style="margin-top:12px"><button class="btn secondary" onclick="answer(true)">A. Photosynthesis</button><button class="btn secondary" onclick="answer(false)">B. Respiration</button><button class="btn secondary" onclick="answer(false)">C. Transpiration</button><button class="btn secondary" onclick="answer(false)">D. Fermentation</button></div></div><div class="span-4 card"><h3 class="section-title">Practice stats</h3><div class="metric">${data.scores.filter(x=>x.type==="q").length}</div><p class="muted">questions attempted</p><button class="btn" onclick="toast('Add your own question bank in app.js')">＋ Add questions</button></div></div>`}
function tests(){return `<div class="grid"><div class="span-5 card"><h3 class="section-title">Add Mock Test</h3><div class="stack"><input class="input" id="testName" placeholder="Test name"><input class="input" id="testScore" type="number" placeholder="Score / 720"><input class="input" id="testDate" type="date"><button class="btn" onclick="addTest()">Save test</button></div></div><div class="span-7 card"><h3 class="section-title">Mock history</h3>${data.scores.filter(x=>x.type==="test").length?`<table class="table"><tr><th>Test</th><th>Score</th><th>Date</th></tr>${data.scores.filter(x=>x.type==="test").map(x=>`<tr><td>${esc(x.name)}</td><td><b>${x.score}</b></td><td>${x.date||"-"}</td></tr>`).join("")}</table>`:`<div class="empty">No mock tests recorded yet.</div>`}</div></div>`}
function performance(){let tests=data.scores.filter(x=>x.type==="test");let avg=tests.length?Math.round(tests.reduce((a,b)=>a+Number(b.score),0)/tests.length):0;return `<div class="grid"><div class="span-4 card"><div class="small muted">Average mock score</div><div class="metric blue">${avg}</div></div><div class="span-4 card"><div class="small muted">Mocks attempted</div><div class="metric">${tests.length}</div></div><div class="span-4 card"><div class="small muted">Target</div><div class="metric accent">${data.profile.target}</div></div><div class="span-12 card"><h3 class="section-title">Subject snapshot</h3><div class="cards-row">${["Physics","Chemistry","Biology"].map(s=>`<div class="subject"><b>${s}</b><div class="metric">${data.subject[s]}%</div><div class="progress"><i style="width:${data.subject[s]}%"></i></div></div>`).join("")}</div></div></div>`}
function streak(){return `<div class="grid"><div class="span-6 card"><div class="small muted">Current study streak</div><div class="big orange">${data.streak} days 🔥</div><p class="muted">Keep logging study hours every day.</p><button class="btn" onclick="incrementStreak()">🔥 Mark today studied</button></div><div class="span-6 card"><h3 class="section-title">Habit checklist</h3><div class="list">${["NCERT revision","50+ MCQs","Error log review","Focused study"].map(x=>`<label class="task"><input type="checkbox"> ${x}</label>`).join("")}</div></div></div>`}
let timer={sec:1500,running:false,id:null};
function pomodoro(){return `<div class="grid"><div class="span-8 card timer"><span class="pill">FOCUS SESSION</span><div class="timer-display" id="timer">${fmt(timer.sec)}</div><div class="toggle"><button class="chip active" onclick="setTimer(25)">25 min</button><button class="chip" onclick="setTimer(50)">50 min</button><button class="chip" onclick="setTimer(5)">5 min</button></div><br><button class="btn" onclick="toggleTimer()">${timer.running?"Pause":"Start Focus"}</button> <button class="btn secondary" onclick="resetTimer()">Reset</button></div><div class="span-4 card"><h3 class="section-title">Focus tips</h3><div class="list">${["Phone away","One chapter only","Active recall","Log your session"].map(x=>`<div class="task">✓ ${x}</div>`).join("")}</div></div></div>`}
function progress(){let vals=data.logs.slice(-7);if(!vals.length)vals=[0,0,0,0,0,0,0];let max=Math.max(1,...vals);return `<div class="grid"><div class="span-8 card"><h3 class="section-title">Last 7 study logs</h3><div class="bar-chart">${vals.map((v,i)=>`<div class="bar" style="height:${Math.max(8,v/max*145)}px"><span>${v}h</span></div>`).join("")}</div></div><div class="span-4 card"><h3 class="section-title">Overall progress</h3>${["Biology","Chemistry","Physics"].map(s=>`<div class="stack" style="margin-bottom:15px"><div class="row"><b>${s}</b><span>${data.subject[s]}%</span></div><div class="progress"><i style="width:${data.subject[s]}%"></i></div></div>`).join("")}</div></div>`}
function settings(){return `<div class="grid"><div class="span-6 card"><h3 class="section-title">Profile</h3><div class="stack"><input class="input" id="name" value="${esc(data.profile.name)}" placeholder="Name"><input class="input" id="handle" value="${esc(data.profile.handle)}" placeholder="@handle"><input class="input" id="target" type="number" value="${data.profile.target}" placeholder="Target score"><input class="input" id="college" value="${esc(data.profile.college)}" placeholder="Dream college"><button class="btn" onclick="saveSettings()">Save settings</button></div></div><div class="span-6 card"><h3 class="section-title">Data</h3><p class="muted">Everything is stored locally on this device/browser.</p><button class="btn secondary" onclick="exportData()">Export data</button> <button class="btn danger" onclick="resetData()">Reset all data</button></div></div>`}
function addTask(){let v=$("#quickTask")?.value.trim();if(!v)return;data.tasks.push({text:v,done:false});save();showPage("dashboard");toast("Task added")}
function addTaskFromPlanner(){let v=$("#taskInput").value.trim();if(!v)return;data.tasks.push({text:v,done:false});save();showPage("planner")}
function toggleTask(i){data.tasks[i].done=!data.tasks[i].done;save();showPage("planner")}
function deleteTask(i){data.tasks.splice(i,1);save();showPage("planner")}
function updateNcert(s,v){data.ncert[s]=Number(v);save();showPage("ncert")}
function chapterDone(s,i,v){toast(v?`${s} chapter ${i+1} completed`:`${s} chapter ${i+1} reopened`)}
function saveSubjectNotes(s){localStorage.setItem("notes_"+s,$("#notes-"+s).value);toast("Notes saved")}
function answer(ok){data.scores.push({type:"q",correct:ok});save();toast(ok?"Correct! 🎉":"Review the concept.")}
function addTest(){let name=$("#testName").value.trim(),score=Number($("#testScore").value);if(!name||!score)return toast("Enter test name and score");data.scores.push({type:"test",name,score,date:$("#testDate").value});save();showPage("tests");toast("Mock saved")}
function logHours(){let h=Number($("#hoursInput").value);if(!h)return;data.hours=h;data.logs.push(h);save();showPage("planner");toast("Study hours saved")}
function incrementStreak(){data.streak++;save();showPage("streak");toast("Streak updated 🔥")}
function saveSettings(){data.profile={name:$("#name").value,handle:$("#handle").value,target:Number($("#target").value)||720,college:$("#college").value};save();toast("Settings saved");showPage("dashboard")}
function exportData(){let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Ayush9845-NEET-data.json";a.click()}
function resetData(){if(confirm("Reset all tracker data?")){data=structuredClone(defaults);save();showPage("dashboard");toast("Data reset")}}
function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function setTimer(m){clearInterval(timer.id);timer.sec=m*60;timer.running=false;showPage("pomodoro")}
function toggleTimer(){if(timer.running){clearInterval(timer.id);timer.running=false}else{timer.running=true;timer.id=setInterval(()=>{if(timer.sec>0){timer.sec--;let el=$("#timer");if(el)el.textContent=fmt(timer.sec)}else{clearInterval(timer.id);timer.running=false;toast("Focus session complete 🎉")}},1000)};showPage("pomodoro")}
function resetTimer(){clearInterval(timer.id);timer.sec=1500;timer.running=false;showPage("pomodoro")}
function wire(){document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page))}
$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");
$("#today").textContent=new Date().toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"});
showPage("dashboard");